apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.labels.app }}
    type: {{ .Values.deployment.labels.type }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  strategy:
    type: {{ .Values.deployment.strategy }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
        type: {{ .Values.deployment.labels.type }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.image.containerName }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 3
          envFrom:
            - secretRef:
                name: {{ .Values.image.secretName }}
      restartPolicy: Always
