apiVersion: v1
kind: Service
metadata:
  labels:
    app: { { .Values.deployment.labels.app } }
  name: { { .Values.service.name } }
spec:
  ports:
    - port: { { .Values.service.port } }
      protocol: TCP
      targetPort: { { .Values.image.containerPort } }
  selector:
    app: { { .Values.deployment.labels.app } }
  sessionAffinity: None
  type: LoadBalancer
