replicaCount: 1

image:
  containerName: nextjs
  repository: icanjump/myhtra-nextjs
  pullPolicy: Always
  tag: "latest"  
  containerPort: 3000

service:
  type: LoadBalancer 
  port: 80

resources: {}

deployment:
  replicas: 1
  strategy: Recreate
  name: myhtra-deployment
  labels:
    app: myhtra
    type: frontend

service:
  name: myhtra-service
  port: 80

ingress:
  name: myhtra-ingress
  secretName: www-tls

podLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  labels:
    azure.workload.identity/use: "true"