image:
  containerName: nextjs
  repository: icanjump/myhtra-nextjs
  pullPolicy: Always
  tag: 'latest'
  containerPort: 3000
  secretName: myhtra-nextjs-environment

service:
  name: myhtra-service
  type: LoadBalancer
  port: 80

resources: {}

deployment:
  replicas: 1
  strategy: Recreate
  name: myhtra-deployment
  labels:
    app: myhtra
    type: frontend

# Does cert issuer handles this
ingress:
  name: myhtra-ingress
  secretName: www-tls

# For TLS
podLabels:
  azure.workload.identity/use: 'true'
serviceAccount:
  labels:
    azure.workload.identity/use: 'true'
